<?php

// Language definitions used in admin-options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'Loš HTTP_REFERER. Ako ste premještali ove forume iz jedne na drugu lokaciju ili mijenjali domene, morate ručno podesiti Početni URL u bazi (tražite o_base_url u config tabeli) i onda očistite cache brisanjem svih .php fajlova u /cache direktoriju.',
'Must enter title message'			=>	'Morate unijeti naslov foruma.',
'Invalid e-mail message'			=>	'Admin email adresa koju ste unijeli je neispravna.',
'Invalid webmaster e-mail message'	=>	'Webmaster email adresa koju ste unijeli je neispravna.',
'SMTP passwords did not match'		=>	'Morate unijeti istu SMTP lozinku dva puta da je promijenite.',
'Enter announcement here'			=>	'Unesite obavještenje ovdje.',
'Enter rules here'					=>	'Unesite pravila ovdje.',
'Default maintenance message'		=>	'Forumi su trenutno ugašeni zbog redovnog održavanja. Molimo navratite opet za nekoliko minuta.',
'Timeout error message'				=>	'Vrijednost "Timeout online" mora biti manje od vrijednosti "Timeout posjete".',
'Options updated redirect'			=>	'Opcije snimljene. Preusmjeravam…',
'Options head'						=>	'Opcije',

// Essentials section
'Essentials subhead'				=>	'Osnovno',
'Board title label'					=>	'Naslov foruma',
'Board title help'					=>	'Naslov ovog foruma (prikazan na vrhu svake stranice). Ovo polje <strong>ne može</strong> sadržavati HTML.',
'Board desc label'					=>	'Opis foruma',
'Board desc help'					=>	'Kratki opis foruma (prikazan na vrhu svake stranice). Ovo polje može sadržavati HTML.',
'Base URL label'					=>	'Bazni URL',
'Base URL help'						=>	'Kompletan URL foruma bez prateće kose crte (npr. http://www.mojadomena.com/forum). Mora biti ispravno da bi sve administratorske i moderatorke mogućnosti funkcionirale. Ako dobivate "Bad referer" greske, vjerojatno je neispravno.',
'Timezone label'					=>	'Pretpostavljena vremenska zona',
'Timezone help'						=>	'Pretpostavljena vremenska zona za goste i korisnike koji se pokušavaju registrirati na forum.',
'DST label'							=>	'Namjesti DST',
'DST help'							=>	'Provjerite da li je čuvanje dnevnog vremena omogućeno (napreduje za 1 sat).',
'Language label'					=>	'Pretpostavljeni jezik',
'Language help'						=>	'Pretpostavljeni jezik za goste i korisnike koji nisu promijenili pretpostavljeni jezik u svojim profilima. Ako uklonite jezični paket, ovo je potrebno izmijeniti.',
'Default style label'				=>	'Pretpostavljeni stil',
'Default style help'				=>	'Pretpostavljeni stil za goste i korisnike koji nisu promijenili pretpostavljenu vrijednost u svojim profilima.',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'							=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'							=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Pacific',
'UTC-07:00'							=>	'(UTC-07:00) Mountain',
'UTC-06:00'							=>	'(UTC-06:00) Central',
'UTC-05:00'							=>	'(UTC-05:00) Eastern',
'UTC-04:00'							=>	'(UTC-04:00) Atlantic',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'							=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'							=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'							=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'								=>	'(UTC) Western European, Greenwich',
'UTC+01:00'							=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'							=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'							=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'							=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'							=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'							=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'							=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'							=>	'(UTC+09:30) Australian Central',
'UTC+10:00'							=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'							=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'							=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'							=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'							=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'							=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'							=>	'(UTC+14:00) Line Islands',

// Timeout Section
'Timeouts subhead'					=>	'Vrijeme i vrijeme čekanja',
'Time format label'					=>	'Format vremena',
'PHP manual'						=>	'PHP priručnik',
'Time format help'					=>	'[Trenutni format: %s]. Pogledajte %s za opcije formatiranja.',
'Date format label'					=>	'Format datuma',
'Date format help'					=>	'[Trenutni format: %s]. Pogledajte %s za opcije formatiranja.',
'Visit timeout label'				=>	'Visit timeout',
'Visit timeout help'				=>	'Broj sekundi koliko korisnik treba biti odsutan prije nego se njegovo/njezino zadnje vrijeme posjete ne izmijeni (primarno utječe na indikatore novih poruka).',
'Online timeout label'				=>	'Online vrijeme čekanja',
'Online timeout help'				=>	'Broj sekundi koliko korisnik treba biti odsutan da bi se uklonio iz liste korisnika koji su online.',
'Redirect time label'				=>	'Vrijeme preusmjeravanja',
'Redirect time help'				=>	'Broj sekundi koje treba pričekati da prođu prije preusmjeravanja. Ako je podešeno na 0 stranica preusmjeravanja neće biti prikazana (nije preporučeno).',

// Display Section
'Display subhead'					=>	'Prikaz',
'Version number label'				=>	'Broj verzije',
'Version number help'				=>	'Prikaži FluxBB broj verzije u podnožju.',
'Info in posts label'				=>	'Informacije o korisnicima u postovima',
'Info in posts help'				=>	'Prikaži informacije o korisniku koji je postavio post ispod korisničkog imena u pregledu teme. Informacije koje su prikazene su lokacija, datum registracije, broj postova i kontakt linkovi (email i URL).',
'Post count label'					=>	'Broj postova korisnika',
'Post count help'					=>	'Prikazuje broj postova koji je korisnik napravio (uključuje pregled tema, profil i listu korisnika).',
'Smilies label'						=>	'Smajlići u postovima',
'Smilies help'						=>	'Konvertiranje smajlića u male grafičke ikone.',
'Smilies sigs label'				=>	'Smajlići u potpisima',
'Smilies sigs help'					=>	'Pretvori smajliće u male grafičke ikone na korisničkim potpisima.',
'Clickable links label'				=>	'Omogući klikabilne linkove',//kralj
'Clickable links help'				=>	'Kada je omogućeno, FluxxBB će automatski detektirati bilo kakve URL-ove u postu i napraviti ih klikabilnim.',//opet kralj
'Topic review label'				=>	'Pregled tema',
'Topic review help'					=>	'Maksimalan broj postova za prikaz prilikom postavljanja posta (prvo najnoviji). Postavite na 0 da onemogućite.',
'Topics per page label'				=>	'Teme po stranici',
'Topics per page help'				=>	'Pretpostavljeni broj tema za prikaz na stranici foruma. Korisnici mogu izmijeniti ovu postavku.',
'Posts per page label'				=>	'Postova po stranici',
'Posts per page help'				=>	'Pretpostavljeni broj postova za prikaz na stranici unutar teme. Korisnici mogu izmijeniti ovu opciju.',
'Indent label'						=>	'Veličina indenta',
'Indent help'						=>	'Ako je postavljeno na 8, regularni tab ce biti korišten prilikom prikaza teksta sa [code][/code] tagovima. Inače će ovoliko biti korišteno za indentovanje teksta.',
'Quote depth label'					=>	'Maksimalna [quote] dubina',
'Quote depth help'					=>	'Maksimalan broj puta koliko [quote] tag moze ići unutar drugog [quote] taga, ijedan dublji tag od ovoga će bit odbačen.',

// Features section
'Features subhead'					=>	'Mogućnosti',
'Quick post label'					=>	'Brzi post',
'Quick post help'					=>	'Kada je omogućeno, FluxBB ce dodati formu za brzi post na dnu svake teme. Ovako korisnici mogu direktno odgovoriti na temu.',
'Users online label'				=>	'Online korisnici',
'Users online help'					=>	'Prikaži informacije na indeksnoj stranici o gostima i registriranim korisnicima koji trenutačno pregledavaju forum.',
'Censor words label'				=>	'Cenzuriranje riječi',
'Censor words help'					=>	'Omogućite ovo da cenzurirate specificirane riječi na forumu. Pogledajte %s za više informacija.',
'Signatures label'					=>	'Potpisi',
'Signatures help'					=>	'Dozvolite korisnicima dodavanje potpisa na njihove postove.',
'User ranks label'					=>	'Korisnički rankovi',
'User ranks help'					=>	'Omogućite ovo da koristite korisničke rankove. Pogledajte %s za više informacija.',
'User has posted label'				=>	'Korisnik je postavio post ranije',
'User has posted help'				=>	'Ova mogućnost prikazuje točku ispred tema u viewforum.php u slučaju da je trenutno prijavljeni korisnik postavio u tu temu ranije. Onemogućite ako server ima visoku potrošnju resursa.',
'Topic views label'					=>	'Pogledi na teme',
'Topic views help'					=>	'Pratite broj pogleda na temu. Onemogućite ako server proživljava visoku potrošnju resursa.',
'Quick jump label'					=>	'Brzi skok',
'Quick jump help'					=>	'Omogućite brzi skok (skok na forum) padajuću listu.',
'GZip label'						=>	'GZip izlaz',
'GZip help'							=>	'Kada je omogućeno, FLuxBB će kompresovati izlaz prema pregledniku pomoću gzip-a. Ovo će smanjiti potrošnju veze ali koristi malo više CPU-a. Ova opcija zahtjeva PHP konfiguriran sa zlib (--with-zlib). Naznaka: Ako već koristite Apache modul mod_gzip ili mod_deflate za kompresovanje PHP skripti onda ova opcija treba biti onemogućena.',
'Search all label'					=>	'Pretraži sve forume',
'Search all help'					=>	'Kada je onemogućeno, pretrage će biti omogućene samo po jednom forumu odjednom. Onemogućite ako je trošenje resursa servera visoko zbog mnogo pretraživanja.',
'Menu items label'					=>	'Dodani elementi menija',
'Menu items help'					=>	'Unošenjem HTML hiperlinkova u ovu kućicu za tekst, bilo koji broj elemenata se mogu dodati na navigacijski meni na vrhu svake stranice. Format dodavanja novih linkova je X = &lt;a href="URL"&gt;LINK&lt;/a&gt; gdje je X pozicija na kojoj će link biti umetnut. (npr. 0 za umetanje na početak i 2 za umetanje iza "Lista korisnika"). Odvojite unos sa novim redom.',

// Feeds section
'Feed subhead'						=>	'Sindikacija',
'Default feed label'				=>	'Pretpostavljena vrsta prikaza vijesti',
'Default feed help'					=>	'Izaberite vrstu prikaza sindikacijskih vijesti. Naznaka: Odabiranje opcije "Ništa" neće onemogućiti prikaz vijesti, samo ih sakriti po pretpostavci.',
'None'								=>	'Ništa',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',
'Feed TTL label'					=>	'Vrijeme spremanja vijesti u cache',
'Feed TTL help'						=>	'Vijesti mogu biti spasene u cache da bi se smanjila potrošnja resursa.',
'No cache'							=>	'Bez cachea',
'Minutes'							=>	'%d minuta',

// Reports section
'Reports subhead'					=>	'Izvješća',
'Reporting method label'			=>	'Metoda za izvješća',
'Internal'							=>	'Interno',
'By e-mail'							=>	'Email',
'Both'								=>	'Oboje',
'Reporting method help'				=>	'Izaberite metodu za rukovanje izvještaja vezanih za temu/post. Možete birati da li će izvješća tema/postova biti rukovana od strane internog sistema za izvještaje, poslani na adresu mail liste (vidite dolje) ili oboje.',
'Mailing list label'				=>	'Mail lista',
'Mailing list help'					=>	'Lista prijavljenih korisnika odvojena zarezom. Korisnici na ovoj listi su primatelji izvještaja.',

// Avatars section
'Avatars subhead'					=>	'Avatari',
'Use avatars label'					=>	'Koristiti avatare',
'Use avatars help'					=>	'Kada je omogućeno, korisnicima će biti omogućeno uploadovanje avatara koji ce biti prikatan unutar njihovog naziva/ranka.',
'Upload directory label'			=>	'Upload direktorij',
'Upload directory help'				=>	'Upload direktorij za avatare (relativan u odnosu na FluxBB direktorij). PHP mora imati ovlaštenje za pisanje u ovaj direktorij.',
'Max width label'					=>	'Maksimalna širina',
'Max width help'					=>	'Maksimlna dozvoljena širina avatara u pikselima (60 preporučeno)',
'Max height label'					=>	'Maksimalna visina',
'Max height help'					=>	'Maksimalna dozvoljena visina avatara u pikselima (60 preporučeno).',
'Max size label'					=>	'Maksimalna veličina',
'Max size help'						=>	'Maksimalna dozvoljena veličina avatara u bajtovima (10240 preporučeno).',

// E-mail section
'E-mail subhead'					=>	'Email',
'Admin e-mail label'				=>	'Admin email',
'Admin e-mail help'					=>	'Email adresa administratora foruma.',
'Webmaster e-mail label'			=>	'Webmaster email',
'Webmaster e-mail help'				=>	'Ovo je adresa na koju ce sve poruke na forumu biti referencirane.',
'Forum subscriptions label'			=>	'Prijave na forume',
'Forum subscriptions help'			=>	'Omogućite korisnicima da se prijave na forume (primanje email poruke kada netko započne novu temu).',
'Topic subscriptions label'			=>	'Prijave na teme',
'Topic subscriptions help'			=>	'Omogućite korisnicima da se prijave na teme (primanje email poruke kada netko odgovori).',
'SMTP address label'				=>	'SMTP adresa servera',
'SMTP address help'					=>	'Adresa vanjskog SMTP servera za slanje email poruka. Možete specificirati broj porta ručno ako SMTP server ne koristi pretpostavljeni port 25 (primjer: mail.mojhost.com:3580). Ostavite prazno u slučaju da koristite lokalni mail program.',
'SMTP username label'				=>	'SMTP korisničko ime',
'SMTP username help'				=>	'Korisničko ime za SMTP server. Unesite samo korisničko ime ako SMTP server to zahtjeva (većina servera <strong>ne</strong> zahtjeva autentifikaciju).',
'SMTP password label'				=>	'SMTP lozinka',
'SMTP change password help'			=>	'Označite ovo ako želite promijeniti ili ukloniti sačuvanu trenutnu lozinku.',
'SMTP password help'				=>	'Lozinka za SMTP server. Unijeti samo ako SMTP server zahtjeva (većina servera <strong>ne</strong> zahtjeva autentifikaciju). Molim unesite vašu lozinku dvaput za potvrdu.',
'SMTP SSL label'					=>	'Ekriptiraj SMTP koristeći SSL',
'SMTP SSL help'						=>	'Enkriptira konekciju prema SMTP koristeći SSL. Koristit samo kada je vaš SMTP server zahtjeva i vaša verzija PHP-a podržava SSL.',

// Registration Section
'Registration subhead'				=>	'Registracija',
'Allow new label'					=>	'Dozvoli nove registracije',
'Allow new help'					=>	'Kontrola da li ovaj forum prihvaća nove registracije. Onemogućiti samo u posebnim uvijetima.',
'Verify label'						=>	'Potvrda registracije',
'Verify help'						=>	'Kada je omogućeno, korisnicima je poslana nasumična lozinka kada se registriraju. Mogu se prijaviti ili promijeniti lozinku unutar svog profila kako žele. Ova mogućnost također zahtjeva korisnicima da potvrde novu email adresu ako požele promijeniti onu sa kojom su se registrirali. Ovo je efektivan način spriječavanja zloupotrebe registracije i potvrđivanja da su svi korisnici unijeli "ispravnu" email adresu u svojim profilima.',
'Report new label'					=>	'Obavještenja o novoj registraciji',
'Report new help'					=>	'Ako je omogućeno, FluxBB će obavijestiti korisnika na mail listu (pogledajte iznad) kada se novi korisnik registrira na forum.',
'Use rules label'					=>	'Pravila za forumske korisnike',
'Use rules help'					=>	'Kada je omogućeno, korisnici se moraju složiti sa setom pravila kada se registriraju (unesite text ispod). Pravila će uvijek biti dostupna kroz link u navigacijskoj tablici na vrhu svake stranice.',
'Rules label'						=>	'Unesite svoja pravila ovdje.',
'Rules help'						=>	'Ovdje možete unijeti bilo kakva pravila ili druge informacije koje korisnik može pregledati i prihvatiti prilikom registracije. Ako ste omogućili pravila iznad morate unijeti nesto ovdje inače će biti onemogućeno. Ovaj tekst neće biti parsiran kao regularni postovi i može sadržavati HTML.',
'E-mail default label'				=>	'Pretpostavljene postavke za email',
'E-mail default help'				=>	'Izaberite pretpostavljenu postavku za registraciju novih korisnika.',
'Display e-mail label'				=>	'Prikaži email adresu drugim korisnicima.',
'Hide allow form label'				=>	'Sakrij email adresu ali omogući email formu.',
'Hide both label'					=>	'Sakrij email adresu i onemogući email formu.',

// Announcement Section
'Announcement subhead'				=>	'Obavještenja',
'Display announcement label'		=>	'Prikaži obavještenje',
'Display announcement help'			=>	'Omogućite ovu opciju da prikažete na forumima poruku ispod.',
'Announcement message label'		=>	'Poruka za obavještenje',
'Announcement message help'			=>	'Ovaj tekst neće biti parsiran kao regularni postovi i može sadržavati HTML.',

// Maintenance Section
'Maintenance subhead'				=>	'Održavanje',
'Maintenance mode label'			=>	'Mod održavanja',
'Maintenance mode help'				=>	'Kada je omogućeno, forumi će biti dostupni samo administratorima. Ovo se treba koristiti kada je forum nepristupačan zbog održavanja. <strong>UPOZORENJE! Ne odjavljujte se kada su forumi u modu održavanja.</strong> Nećete se moći ponovno prijaviti.',
'Maintenance message label'			=>	'Poruka za održavanje',
'Maintenance message help'			=>	'Poruka koja će biti prikazana korisnicima kada su forumi u modu održavanja. Ako se polje ostavi prazno pretpostavljena poruka ce biti korištena. Ovaj tekst neće biti parsiran kao regularni postovi i može sadržavati HTML.',
);
