<?php

// Language definitions used in admin-users.php
$lang_admin_users = array(

'Non numeric message'		=>	'Unijeli ste nenumeričku vrijednost u kolonu koja mora biti samo numerička.',
'Invalid date time message'	=>	'Vrijeme/datum koji ste unijeli nije validno.',
'Not verified'				=>	'Nije verifikovano',

// Actions: mass delete/ban etc.
'No users selected'			=>	'Nije odabran korisnik.',
'No move admins message'	=>	'Zbog sigurnosnih razloga nije vam dopušteno da odjednom premještate više administratora u drugu grupu. Ako želite da premjestite ove administratore to možete uraditi na njihovim odgovarajućim korisničkim profilima.',
'No delete admins message'	=>	'Administratori se ne mogu obrisati. Da bi obrisali administratore, prvo ih morate premjestiti u neku drugu grupu korisnika.',
'No ban admins message'		=>	'Administratori se ne mogu banovati. Da bi banovali administratore, prvo ih morate premjestiti u neku drugu grupu korisnika.',
'No ban mods message'		=>	'Moderatori se ne mogu banovati. Da bi banovali moderatore, prvo ih morate premjestiti u neku drugu grupu korisnika.',
'Move users'				=>	'Promijeni korisničku grupu',
'Move users subhead'		=>	'Odaberi novu korisničku grupu',
'New group label'			=>	'Nova grupa',
'New group help'			=>	'Odaberite grupu u koju želite da premjestite odabrane korisnike. Zbog sigurnosnih razloga nije dopušteno da odjednom premještate više korisnika u administratorsku grupu.',
'Invalid group message'		=>	'Neispravan ID grupe.',
'Users move redirect'		=>	'Korisnička grupa promijenja. Preusmjeravam …',
'Delete users'				=>	'Obriši korisnike',
'Confirm delete legend'		=>	'Važno: pročitaj prije brisanja korisnika',
'Confirm delete info'		=>	'Molimo potvrdite da želite obrisati ove korisnike.',
'Delete posts'				=>	'Obriši sve postove i poruke koje su napravili ovi korisnici.',
'Delete warning'			=>	'Upozorenje! Obrisani korisnici i/ili poruke ne mogu biti povraćeni. Ako odaberete da nećete obrisati poruke koje su postavili ovi korisnici, u tom slučaju poruke se mogu kasnije obrisati i to samo manuelno.',
'Users delete redirect'		=>	'Korisnici obrisani. Preusmjeravam …',
'Ban users'					=>	'Banuj korisnike',
'Message expiry subhead'	=>	'Ban poruka i istek',
'Ban message label'			=>	'Ban poruka',
'Ban message help'			=>	'Poruka koja će biti prikazana banovanim korisnicima kada ponovo posjete forum',
'Expire date label'			=>	'Datum isteka',
'Expire date help'			=>	'Datum automatskog ukanjanja banova (format: yyyy-mm-dd). Ostavite prazno za ručno uklanjanje.',
'Ban IP label'				=>	'Banuj IP adrese',
'Ban IP help'				=>	'Takođe banuj IP adrese banovanih korisnika da bi im otežali kreiranje novog naloga.',
'Invalid date message'		=>	'Unijeli ste neispravan datum isteka.',
'Invalid date reasons'		=>	'Format treba ida bude YYYY-MM-DD i datum mora biti barem jedan dan u budućnosti.',
'Users banned redirect'		=>	'Korisnik banovan. Preusmjeravam …',

'User search head'			=>	'Pretraga korisnika',
'User search subhead'		=>	'Unesite kriterije pretrage',
'User search info'			=>	'Traži korisnike u bazi podataka. Možete unijeti jedan ili više izraza za pretraživanje. Zamjenski znakovi u obliku zvjezdica (*) su prihvaćeni.',
'Username label'			=>	'Korisničko ime',
'E-mail address label'		=>	'Email adresa',
'Title label'				=>	'Titula',
'Real name label'			=>	'Pravo ime',
'Website label'				=>	'Web stranica',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'Lokacija',
'Signature label'			=>	'Potpis',
'Admin note label'			=>	'Administratorska napomena',
'Posts more than label'		=>	'Broj poruka veći od',
'Posts less than label'		=>	'Broj poruka manji od',
'Last post after label'		=>	'Zadnja poruka je poslije',
'Date help'					=>	'(yyyy-mm-dd hh:mm:ss)',
'Last post before label'	=>	'Zadnja poruka je prije',
'Registered after label'	=>	'Registrovan poslije',
'Registered before label'	=>	'Registrovan prije',
'Order by label'			=>	'Sortiraj po',
'Order by username'			=>	'Korisničko ime',
'Order by e-mail'			=>	'Email',
'Order by posts'			=>	'Broje poruka',
'Order by last post'		=>	'Zadnja poruka',
'Order by registered'		=>	'Registrovan',
'Ascending'					=>	'Rastući',
'Descending'				=>	'Opadajući',
'User group label'			=>	'Korisnička grupa',
'All groups'				=>	'Sve grupe',
'Unverified users'			=>	'Neprovjereni korisnici',
'Submit search'				=>	'Pošalji pretragu',
'IP search head'			=>	'IP pretraga',
'IP search subhead'			=>	'Unesite IP adresu za pretraživanje',
'IP address label'			=>	'IP adresa',
'IP address help'			=>	'IP adresa koju po kojoj se traži u bazi poruka.',
'Find IP address'			=>	'Nađi IP adresu',

'Results head'				=>	'Rezultati pretrage',
'Results username head'		=>	'Korisničko ime',
'Results e-mail head'		=>	'Email',
'Results title head'		=>	'Titula/status',
'Results posts head'		=>	'Poruke',
'Results admin note head'	=>	'Admin napomena',
'Results actions head'		=>	'Akcije',
'Results IP address head'	=>	'IP adresa',
'Results last used head'	=>	'Zadnje korišteno',
'Results times found head'	=>	'Puta nađeno',
'Results action head'		=>	'Akcija',
'Results find more link'	=>	'Nađi više korisnika sa ovom IP adresom',
'Results no posts found'	=>	'Na forumu trenutno nema poruka od ovog korisnika.',
'Select'					=>	'Odaberi',
'Select all'				=>	'Odaberi sve',
'Unselect all'				=>	'Poništi odabir svega',
'Ban'						=>	'Ban',
'Delete'					=>	'Brisanje',
'Change group'				=>	'Promijeni grupu',
'Bad IP message'			=>	'Isporučena adresa nije u korektnom formatu.',
'Results view IP link'		=>	'Pregledaj IP statistiku',
'Results show posts link'	=>	'Prikaži poruke',
'Results guest'				=>	'Gost',
'Results no IP found'		=>	'Isporučena adresa nije pronađena u bazi podataka.',
'No match'					=>	'Ne poklapa se'

);
