<?php

// Language definitions used in admin-groups.php
$lang_admin_groups = array(

'Must enter title message'		=>	'Morate unijeti naslov grupe.',
'Title already exists message'	=>	'Već postoji grupa sa naslovom <strong>%s</strong>.',
'Default group redirect'		=>	'Standardna grupa snimljena. Preusmjeravam …',
'Cannot remove default message'	=>	'Standardna grupa ne može biti obrisana. Da obrišete ovu grupu morate prvo postaviti drugu grupu kao standardnu.',
'Group removed redirect'		=>	'Grupa obrisana. Preusmjeravam …',
'Group added redirect'			=>	'Grupa dodana. Preusmjeravam …',
'Group edited redirect'			=>	'Grupa snimljena. Preusmjeravam …',

'Add groups head'				=>	'Dodaj/podesi grupe',
'Add group subhead'				=>	'Dodaj novu grupu',
'New group label'				=>	'Baziraj novu grupu na',
'New group help'				=>	'Izaberi korisničku grupu iz koje će nova grupa naslijediti postavke permisija. Na sljedećoj stranici možete podesiti postavke permisija.',
'Default group subhead'			=>	'Postavi standardnu grupu',
'Default group label'			=>	'Standardna grupa',
'Default group help'			=>	'Ovo je standardna grupa u koju će korisnici biti dodani nakon registracije. Iz sigurnosnih razloga korisnici ne mogu biti dodani u moderatorsku ili administratorsku grupu odmah nakon registracije.',
'Existing groups head'			=>	'Postojeće grupe',
'Edit groups subhead'			=>	'Izmijeni/obriši grupe',
'Edit groups info'				=>	'Predefinisane grupe Gosti, Administratori, Moderatori i Korisnici ne mogu biti obrisane ali mogu biti izmijenjene. Imajte na umu da u nekim grupama neke postavke nisu dostupne (npr. opcija <em>izmijeni poruke</em> za goste). Administratori uvijek imaju puni pristup.',
'Edit link'						=>	'Izmijeni',
'Delete link'					=>	'Obriši',
'Group delete head'				=>	'Brisanje grupe',
'Confirm delete subhead'		=>	'Potvrdi brisanje grupe',
'Confirm delete info'			=>	'Jeste li sigurni da želite obrisati grupu <strong>%s</strong>?',
'Confirm delete warn'			=>	'UPOZORENJE! Nakon brisanja nije moguće vratiti grupu.',
'Delete group head'				=>	'Obriši grupu',
'Move users subhead'			=>	'Premjesti korisnike trenutno u grupi',
'Move users info'				=>	'Grupa <strong>%s</strong> trenutno ima <strong>%s</strong> članova. Molimo izaberite grupu u koju će ovi članovi biti premješteni nakon brisanja.',
'Move users label'				=>	'Premjesti korisnike u',
'Delete group'					=>	'Obriši grupu',

'Group settings head'			=>	'Postavke grupe',
'Group settings subhead'		=>	'Podesi opcije i permisije grupe',
'Group settings info'			=>	'Opcije i permisije niže su početne za korisničku grupu. Ove opcije se koriste ako nisu postavljene specifične permisije po forumu.',
'Group title label'				=>	'Naziv grupe',
'User title label'				=>	'Naziv korisnika',
'User title help'				=>	'Ovaj naziv će biti prikazan preko čina kog su dobili korisnici u grupi. Ostavite prazno da koristite početni naziv ili čin.',
'Mod privileges label'			=>	'Dodijeli korisniku moderatorske privilegije',
'Mod privileges help'			=>	'Da bi korisnici u ovoj grupi imali moderatorske sposobnosti, on/a mora biti dodijeljen/a moderaciji jednog ili više foruma. Ovo se može postaviti putem administracijske stranice profila korisnika.',
'Edit profile label'			=>	'Dozvoli moderatorima izmjenu korisničkih profila',
'Edit profile help'				=>	'Ukoliko su moderatorske privilegije omogućene, dozvoli korisnicima ove grupe mogućnost izmjene korisničkih profila.',
'Rename users label'			=>	'Dozvoli moderatorima preimenovanje korisničkih imena',
'Rename users help'				=>	'Ukoliko su moderatorske privilegije omogućene, dozvoli korisnicima ove grupe mogućnost izmjenu korisničkih imena.',
'Change passwords label'		=>	'Dozvoli moderatorima izmjenu lozinki',
'Change passwords help'			=>	'Ukoliko su moderatorske privilegije omogućene, dozvoli korisnicima ove grupe mogućnost izmjenu lozinki korisničkih naloga.',
'Ban users label'				=>	'Dozvoli moderatorima banovanje korisnika',
'Ban users help'				=>	'Ukoliko su moderatorske privilegije omogućene, dozvoli korisnicima ove grupe mogućnost banovanja korisnika.',
'Read board label'				=>	'Čitanje foruma',
'Read board help'				=>	'Dozvoli korisnicima u ovoj grupi da otvore forum. Ova postavka važi za sve aspekte stranice i ne može biti promijenjena sa postavkama po specifičnom forumu. Ako je ovo postavljeno na "Ne", korisnici u ovoj grupi će moću samo da se prijave/odjave i registruju.',
'View user info label'			=>	'Pregled korisničkih podataka',
'View user info help'			=>	'Dozvoli korisnicima da vide listu i profile korisnika.',
'Post replies label'			=>	'Odgovaranje na temu',
'Post replies help'				=>	'Dozvoli korisnicima u ovoj grupi da postave odgovore na teme.',
'Post topics label'				=>	'Postavljanje tema',
'Post topics help'				=>	'Dozvoli korisnicima u ovoj grupi da postavljaju nove teme.',
'Edit posts label'				=>	'Izmjena poruka',
'Edit posts help'				=>	'Dozvoli korisnicima u ovoj grupi da mogu izmijeniti vlastite poruke.',
'Delete posts label'			=>	'Brisanje poruka',
'Delete posts help'				=>	'Dozvoli korisnicima u ovoj grupi da mogu brisati vlastite poruke.',
'Delete topics label'			=>	'Brisanje tema',
'Delete topics help'			=>	'Dozvoli korisnicima u ovoj grupi da delete their own topics (including any replies).',
'Set own title label'			=>	'Postavljanje vlastitog naslova',
'Set own title help'			=>	'Dozvoli korisnicima u ovoj grupi da postave vlastiti naslov.',
'User search label'				=>	'Korištenje pretrage',
'User search help'				=>	'Dozvoli korisnicima u ovoj grupi da koriste pretragu.',
'User list search label'		=>	'Pretraga liste korisnika',
'User list search help'			=>	'Dozvoli korisnicima u ovoj grupi da koriste pretragu liste korisnika.',
'Send e-mails label'			=>	'Slanje e-mailova',
'Send e-mails help'				=>	'Dozvoli korisnicima u ovoj grupi da šalju e-mailove drugim korisnicima.',
'Post flood label'				=>	'Interval između odgovora',
'Post flood help'				=>	'Broj sekundi koliko korisnici ove grupe moraju čekati između odgovora. Postavite na 0 da isključite..',
'Search flood label'			=>	'Interval između pretraga',
'Search flood help'				=>	'Broj sekundi koliko korisnici ove grupe moraju čekati između pretraga. Postavite na 0 da isključite..',
'E-mail flood label'			=>	'Interval između e-mailova',
'E-mail flood help'				=>	'Broj sekundi koliko korisnici ove grupe moraju čekati između emailova. Postavite na 0 da isključite..',
'Moderator info'				=>	'Da bi korisnik ove grupe imao moderatorske mogućnosti, imajte na umu da on/a mora biti postavljena za moderatore jednog ili više foruma. Ovo se može podesiti na administracijskoj stranici korisničkog profila.',

);
