<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'Provjeravanje za novu verziju neuspjelo jer \'allow_url_fopen\' je isključena na ovom sistemu.',
'Upgrade check failed message'		=>	'Provjeravanje za novu verziju neuspjelo iz nepoznatih razloga.',
'Running latest version message'	=>	'Imate zadnju verziju FluxBBa.',
'New version available message'		=>	'Izašla je nova verzija FluxBBa. Možete skinuti zadnju verziju na %s.',
'PHPinfo disabled message'			=>	'PHP funkcija phpinfo() je isključena na ovom serveru.',
'Not available'						=>	'Nije dostupno',
'Forum admin head'					=>	'Forum administracija',
'NA'								=>	'N/A',
'Welcome to admin'					=>	'Dobrodošli u FluxBB administracijski control panel. Odavde možete kontrolisati vitalne aspekte vašeg foruma. Ovisno o tome da li ste administrator ili moderator možete:',
'Welcome 1'							=>	'Organizirati kategorije i foruma.',
'Welcome 2'							=>	'Podesiti postavke i preference širom foruma.',
'Welcome 3'							=>	'Kontrolisati permisije za korisnike i goste.',
'Welcome 4'							=>	'Gledati IP statistiku za korisnike.',
'Welcome 5'							=>	'Banovati korisnike.',
'Welcome 6'							=>	'Cenzurisati riječi.',
'Welcome 7'							=>	'Postaviti korisničke činove.',
'Welcome 8'							=>	'Uprostiti stare postove.',
'Welcome 9'							=>	'Održavati prijave za odgovore.',
'Statistics head'					=>	'Statistika',
'FluxBB version label'				=>	'FluxBB verzija',
'Check for upgrade'					=>	'Provjeri za nadogranju',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'Server load',
'Server load data'					=>	'%s - %s korisnik(a) online',
'Environment label'					=>	'Okruženje',
'Environment data OS'				=>	'Operativni sistem: %s',
'Show info'							=>	'Prikaži info',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Akcelerator: %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Baza',
'Database data rows'				=>	'Redove: %s',
'Database data size'				=>	'Veličina: %s',

);
