<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Profil',
'Section essentials'			=>	'Osnovno',
'Section personal'				=>	'Lično',
'Section messaging'				=>	'Instant Messengeri',
'Section personality'			=>	'Avatar/potpis',
'Section display'				=>	'Prikaz',
'Section privacy'				=>	'Privatnost',
'Section admin'					=>	'Administracija',

// Miscellaneous
'Username and pass legend'		=>	'Unesite vaše korisničko ime i šifru',
'Personal details legend'		=>	'Unesite vaše lične detalje',
'Contact details legend'		=>	'Unesite vaše instang messaging detalje',
'User activity'					=>	'Aktivnost korisnika',
'Paginate info'					=>	'Unesite broj tema i poruka za prikaz po stranici.',

// Password stuff
'Pass key bad'					=>	'Navedeni aktivacijski ključ za vašu šifru je netačan ili je istekao. Molimo da ponovite zahtjev za novom šifrom. Ako to ne uspije kontaktirajte administratora foruma na',
'Pass updated'					=>	'Vaša šifra je osvježena. Sada se možete prijaviti sa vašom novom šifrom.',
'Pass updated redirect'			=>	'Šifra osvježena. Preusmjeravam …',
'Wrong pass'					=>	'Pogrešna stara šifra.',
'Change pass'					=>	'Promijeni šifru',
'Change pass legend'			=>	'Unesite i potvrdite vašu novu šifru',
'Old pass'						=>	'Stara šifra',
'New pass'						=>	'Nova šifra',
'Confirm new pass'				=>	'Potvrdi novu šifru',
'Pass info'						=>	'Šifre moraju biti duge najmanje 4 karaktera. Šifre su osjetljive na mala i velika slova.',

// Email stuff
'Email key bad'					=>	'Navedeni aktivacijski ključ za vašu email adresu je netačan ili je istekao. Molimo da ponovite zahtjev za novom email adresom. Ako to ne uspije, kontaktirajte administratora foruma na',
'Email updated'					=>	'Vaša email adresa je osvježena.',
'Activate email sent'			=>	'Email sa instrukcijama za aktivaciju je poslan na navedenu adresu. Ako ga ne dobijete možete kontaktirati administratora na',
'Email legend'					=>	'Unesite vašu novu email adresu',
'Email instructions'			=>	'Biće vam poslan email sa aktivacijskim linkom na vašu novu adresu. Za aktivaciju novog emaila morate kliknuti na link koji ćete dobiti na email.',
'Change email'					=>	'Promijeni email adresu',
'New email'						=>	'Novi email',

// Avatar upload stuff
'Avatars disabled'				=>	'Administrator je onemogućio podršku za avatare.',
'Too large ini'					=>	'Odabrana datoteka je prevelika za učitavanje. Server nije dozvolio učitavanje.',
'Partial upload'				=>	'Odabrana datoteka je samo djelomično učitana. Molimo pokušajte ponovo.',
'No tmp directory'				=>	'PHP nije bio u mogućnosti učitanu datoteku spasiti na privremenu lokaciju.',
'No file'						=>	'Niste odabrali datoteku za učitavanje.',
'Bad type'						=>	'Datoteka koju ste odabrali za učitavanje nije dozvoljene ekstenzije. Dozvoljene ekstenzije su gif, jpeg i png.',
'Too wide or high'				=>	'Datoteka koju se odabrali za učitavanje je šira i/ili duža od dozvoljenog maksimuma',
'Too large'						=>	'Datoteka koju ste odabrali je veća od maksimalne dozvoljene veličine',
'pixels'						=>	'piksela',
'bytes'							=>	'bajta',
'Move failed'					=>	'Server nije uspio snimiti učitanu datoteku. Molimo kontaktirajte administratora foruma na',
'Unknown failure'				=>	'Desila se nepoznata greška. Molimo pokušajte ponovo.',
'Avatar upload redirect'		=>	'Avatar učitan. Preusmjeravam …',
'Avatar deleted redirect'		=>	'Avatar obrisan. Preusmjeravam …',
'Avatar desc'					=>	'Avatar je mala slika koja će biti prikazana ispod vašeg korisničkog imena u vašim porukama. Ne smije biti veća od',
'Upload avatar'					=>	'Učitaj avatar',
'Upload avatar legend'			=>	'Unesite avatar datoteku za učitavanje',
'Delete avatar'					=>	'Obriši avatar', // only for admins
'File'							=>	'Datoteka',
'Upload'						=>	'Učitaj', // submit button

// Form validation stuff
'Forbidden title'				=>	'Naslov koji ste unijeli sadrži zabranjenu riječ. Morate odabrati drugačiji naslov.',
'Profile redirect'				=>	'Profile osvježen. Preusmjeravam …',

// Profile display stuff
'Users profile'					=>	'%s\'s profil',
'Username info'					=>	'Korisnik: %s',
'Email info'					=>	'Email: %s',
'Posts info'					=>	'Poruke: %s',
'Registered info'				=>	'Registrovan: %s',
'Last post info'				=>	'Zadnja poruka: %s',
'Last visit info'				=>	'Zadnja posjeta: %s',
'Show posts'					=>	'Prikaži sve poruke',
'Show topics'					=>	'Prikaži sve teme',
'Show subscriptions'			=>	'Prikaži sve pretplate',
'Realname'						=>	'Pravo ime',
'Location'						=>	'Lokacija',
'Website'						=>	'Web stranica',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Potpis',
'Sig max size'					=>	'Max dužina: %s karaktera / Max linija: %s',
'Avatar legend'					=>	'Postavite opcije prikaza za vaš avatar',
'Avatar info'					=>	'Avatar je mala slika koja će biti prikazana ispod vašeg korisničkog imena u vašim porukama. Možete učitati avatar klikom na link ispod,',
'Change avatar'					=>	'Promijeni avatar',
'Signature legend'				=>	'Sastavite vaš potpis',
'Signature info'				=>	'Potpis je mali dio teksta koji se prikači na kraj vaših poruka. U njega možete unijeti šta želite. Na primjer vaš moto i sl. Do vas je! U potpisu možete koristiti BBCode ako je dozvoljen na ovom posebnom forumu. Možete da vidite opcije koje su dozvoljene/omogućene izlistane ispod, svaki put kada mijenjate vaš potpis.',
'Sig preview'					=>	'Pregled trenutnog potpisa:',
'No sig'						=>	'Trenutno nema sačuvanog potpisa u profilu.',
'Signature quote/code/list/h'	=>	'Quote, code, list i heading BBCodovi nisu dopušteni u potpisima.',
'Topics per page'				=>	'Teme',
'Posts per page'				=>	'Poruke',
'Leave blank'					=>	'Ostavi prazno za korištenje već zadanih forumskih postavki.',
'Subscription legend'			=>	'Postavite pretplatničke opcije',
'Notify full'					=>	'Uključi običnu tekstualnu verziju poruka u pretplaćenim notifikacijskim emailovima.',
'Auto notify full'				=>	'Automatska pretplata na svaku temu na koju odgovorite porukom.',
'Show smilies'					=>	'Prikaži smajlije kao sliku.',
'Show images'					=>	'Prikaži slike u porukama.',
'Show images sigs'				=>	'Prikaži slike u potpisu.',
'Show avatars'					=>	'Prikaži korisničke avatare u porukama.',
'Show sigs'						=>	'Prikaži potpise korisnika.',
'Style legend'					=>	'Odaberite vaš omiljeni stil',
'Styles'						=>	'Stilovi',
'Admin note'					=>	'Admin napomena',
'Pagination legend'				=>	'Unesite opcije numerisanja stranica',
'Post display legend'			=>	'Postavite opcije za prikazivanje poruka',
'Post display info'				=>	'Ukoliko imate slabu Internet konekciju, možete isključiti prikaz slika.',
'Instructions'					=>	'Nakon snimanja profila, bićete ponovo preusmjereni na ovu stranicu.',

// Administration stuff
'Group membership legend'		=>	'Odaberi korisničku grupu',
'Save'							=>	'Snimi',
'Set mods legend'				=>	'Postavi moderatorski pristup',
'Moderator in info'				=>	'Odaberi koje forume ovaj korisnik može moderirati. Napomena: Ovo važi samo za moderatore. Administratori uvijek imaju sva prava u svim forumima.',
'Update forums'					=>	'Osvježi forume',
'Delete ban legend'				=>	'Izbriši (samo administratori) ili banuj korisnika',
'Delete user'					=>	'Obriši korisnika',
'Ban user'						=>	'Banuj korisnika',
'Confirm delete legend'			=>	'Važno: pročitaj prije brisanja korisnika',
'Confirm delete user'			=>	'Potvrdi brisanje korisnika',
'Confirmation info'				=>	'Molimo da potvrdite brisanje korisnika', // the username will be appended to this string
'Delete warning'				=>	'Upozorenje! Obrisani korisnici i/ili poruke ne mogu biti vraćeni. Ako odaberete da ne želite obrisati poruke koje je postavio ovaj korisnik, u tom slučaju poruke kasnije jedino mogu biti ručno obrisane.',
'Delete posts'					=>	'Obriši sve poruke i teme koje je napravio ovaj korisnik.',
'Delete'						=>	'Obriši', // submit button (confirm user delete)
'User delete redirect'			=>	'Korisnik obrisan. Preusmjeravam …',
'Group membership redirect'		=>	'Članstvo grupe snimljeno. Preusmjeravam …',
'Update forums redirect'		=>	'Prava forum moderatora osvježena. Preusmjeravam …',
'Ban redirect'					=>	'Preusmjeravam …',
'No delete admin message'		=>	'Administratori ne mogu biti obrisani. Da bi obrisali ovog korisnika, morate ga prvo prebaciti u drugu korisničku grupu.',

);
