<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Unesite validnu email adresu',
'Email legend 2'			=>	'Unesite i potvrdite validnu email adresu',
'Localisation legend'		=>	'Postavite opcije lokalizacije',
'Time zone'					=>	'Vremenska zona',
'Time zone info'			=>	'Da bi forum korektno prikazivao vremena morate odabrati vašu lokalnu vremensku zonu. Ako je uključeno ljetno računanje vremena trebali bi takođe odabrati i tu opciju.',
'DST'						=>	'Ljetno računanje vremena je u upotrebi (pomjeri vrijeme unaprijed za 1 sat).',
'Time format'				=>	'Format vremena',
'Date format'				=>	'Format datuma',
'Default'					=>	'Podrazumijevani',
'Language'					=>	'Jezik',
'Email setting info'		=>	'Odaberite način prikaza vaše email adrese, da li je vidljiva drugim korisnicima foruma, da li želite da vam ostali korisnici mogu poslati email preko foruma ili ne.',
'Email setting 1'			=>	'Prikaži email adresu.',
'Email setting 2'			=>	'Sakrij email adresu ali dozvoli slanje emaila preko email forme.',
'Email setting 3'			=>	'Sakrij email adresu i zabrani slanje emaila preko email forme.',
'Privacy options legend'	=>	'Postavite vaše opcije privatnosti',
'Confirm pass'				=>	'Potvrdi šifru',

'Username too short'		=>	'Korisnička imena moraju biti duga bar 2 karaktera. Molimo odaberite drugo (duže) korisničko ime.',
'Username too long'			=>	'Korisnička imena ne smiju biti veća od 25 karaktera. Molimo odaberite drugo (kraće) korisničko ime.',
'Username guest'			=>	'Korisničko ime guest je rezervisano. Molimo odaberite drugo korisničko ime.',
'Username IP'				=>	'Korisnička imena ne smiju biti u formatu IP adrese. Molimo odaberite drugo korisničko ime.',
'Username reserved chars'	=>	'Korisnička imena ne smiju sadržavati \', " i [ ili ]. Molimo odaberite drugo korisničko ime.',
'Username BBCode'			=>	'Korisnička imena ne smiju sadržavati bilo koji od BBCode-ova koje forum koristi. Molimo odaberite drugo korisničko ime.',
'Banned username'			=>	'Korisničko ime koje ste unijeli je banovano na ovom forumu. Molimo odaberite drugo korisničko ime.',
'Pass too short'			=>	'Šifre moraju biti duge najmanje 4 karaktera. Molimo odaberite drugu (dužu) šifru.',
'Pass not match'			=>	'Šifre se ne podudaraju',
'Banned email'				=>	'Email adresa koju ste unijeli je banovana na ovom forumu. Molimo odaberite drugu email adresu.',
'Dupe email'				=>	'Neko drugi se već registrovao sa tom email adresom. Molimo odaberite drugu email adresu.',
'Sig too long'				=>	'Potpisi ne mogu biti duži od %1$s karaktera. Molimo skratite vaš potpis za %2$s karaktera.',
'Sig too many lines'		=>	'Potpisi ne mogu imati više od %s linija.',
'Bad ICQ'					=>	'ICQ UIN koji ste unijeli nije validan. Molimo da se vratite i da popravite unos.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
