<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'Pretraga korisnika',
'No search permission'				=>	'Nemate dozvolu da koristite pretragu',
'Search flood'						=>	'Između dva pretraživanja mora proći najmanje %s sekundi. Molimo Vas da pokušate malo kasnije.',
'Search'							=>	'Pretraga',
'Search criteria legend'			=>	'Unesite kriterije vaše pretrage',
'Search info'						=>	'Za pretragu po ključnoj riječi unesite termin ili termine za pretragu, između termina koristiti razmak. Za pretragu po autoru unesite korisničko ime autora čije poruke želite naći. Možete koristiti specijalni simbol * za djelimična poklapanja.',
'Keyword search'					=>	'Pretraga po ključnoj riječi',
'Author search'						=>	'Pretraga po autoru',
'Search in legend'					=>	'Odaberite gdje da tražim',
'Search in info'					=>	'Odaberite u kojem forumu želite da tražim i ako želite pretragu u naslovima tema, tekstu poruka ili oboje.',
'Forum search'						=>	'Forum',
'All forums'						=>	'Svi forumi',
'Search in'							=>	'Pretražuj u',
'Message and subject'				=>	'Tekst poruke i naslov teme.',
'Message only'						=>	'Samo tekst poruke',
'Topic only'						=>	'Samo naslov teme',
'Sort by'							=>	'Sortiraj po',
'Sort order'						=>	'Način sortiranja',
'Search results legend'				=>	'Odaberite prikaz rezultata pretrage',
'Search results info'				=>	'Možete odabrati način sortiranja i pretrage rezultata.',
'Sort by post time'					=>	'Vrijeme slanja',
'Sort by author'					=>	'Autor',
'Sort by subject'					=>	'Naslov',
'Sort by forum'						=>	'Forum',
'Ascending'							=>	'Rastući',
'Descending'						=>	'Opadajući',
'Show as'							=>	'Prikaži rezultate kao',
'Show as topics'					=>	'Naslovi',
'Show as posts'						=>	'Poruke',

// Results
'Search results'					=>	'Rezultati pretrage',
'Search topics'						=>	'Pretražuj naslove',
'Search posts'						=>	'Pretražuj poruke',
'Quick search show_new'				=>	'Novo',
'Quick search show_recent'			=>	'Aktivno',
'Quick search show_unanswered'		=>	'Neodgovoreno',
'Quick search show_replies'			=>	'Poslano',
'Quick search show_user_topics'		=>	'Od %s',
'Quick search show_user_posts'		=>	'Od %s',
'Quick search show_subscriptions'	=>	'Pretplaćeno od %s',
'By keywords show as topics'		=>	'Sa porukama sa ključnim riječima \'%s\'',
'By keywords show as posts'			=>	'Sa ključnim riječima \'%s\'',
'By user show as topics'			=>	'Sa porukama od %s',
'By user show as posts'				=>	'By %s',
'By both show as topics'			=>	'With keywords \'%s\' in posts by %s',
'By both show as posts'				=>	'With keywords \'%s\' by %s',
'No terms'							=>	'U pretragu morate unijeti bar jednu riječ i/ili autora.',
'No hits'							=>	'Bez rezultata.',
'No user posts'						=>	'Ovaj korisnik još uvijek nema poruka na forumu.',
'No user topics'					=>	'Ovaj korisnik nije započeo niti jednu temu na forumu.',
'No subscriptions'					=>	'Ovaj korisnik trenutno nije pretplaćen ni na jednu temu.',
'No new posts'						=>	'Nema novih tema od zadnje posjete.',
'No recent posts'					=>	'Nema novih poruka u posljednja 24 sata.',
'No unanswered'						=>	'Nema neodgovorenih poruka na ovom forumu.',
'Go to post'						=>	'Idi na poruku',
'Go to topic'						=>	'Idi na temu'

);
